services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/docker/web/Dockerfile
    volumes:
      - static:/app/web/static/
      - ./backups:/app/web/backups/
      - ./media:/app/web/media/
      - ./database:/app/web/db/
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./apps/web/.env

  www:
    container_name: www
    build:
      context: .
      dockerfile: apps/docker/www/Dockerfile
    volumes:
      - node_modules:/app/www/node_modules
    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: apps/docker/nginx/Dockerfile
    volumes:
      - static:/app/web/static/
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./webroot:/var/www/html
    ports:
      - 80:80
      - 443:443s
    depends_on:
      - www
      - web
    restart: unless-stopped

volumes:
  static:
  node_modules:
